apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runner
  namespace: github
spec:
  # This will deploy 2 runners now
  replicas: 2
  template:
    spec:
      organization: mlevos-demo